name: data

# on:
#   schedule:
#     - cron: 0 * * * *
#   workflow_dispatch: {}
#   push:
#     paths:
#       - .github/workflows/flat.yml
#       - ./query.sql

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          sql_connstring: ${{ secrets.FLAT_VJEJ8D_CONNSTRING }}
          sql_queryfile: ./query.sql
          downloaded_filename: data.json
